# Tratamento de Erros e Exceções

# sintático - exceção
# "print(x)" nesse caso, x não foi iniciado anteriormente 
n = int(input('Número: ')) #Digitei 'OITO'
# "print(n)" nesse caso, n não é um inteiro e apresenta ValueError
#ZeroDivisionError, no caso de divisões por 0, conforme o próprio nome
